<a href="https://colab.research.google.com/github/nagasri15/TNS-practice-session/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
arr1 = np.array([1,2,3,4])
print(arr1)

[1 2 3 4]


In [6]:
#0-D
arr1 = np.array(5)
print(arr1)

5


In [7]:
#1D
a = np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [9]:
#2D
b = np.array([[2,6,7,4],[3,9,0,7]])
print(b)

[[2 6 7 4]
 [3 9 0 7]]


In [15]:
#3D
c = np.array([[[2,4,5],[0,3,2],[8,9,5]]])
print(c)

[[[2 4 5]
  [0 3 2]
  [8 9 5]]]


In [17]:
#to know dimensions
print(a.ndim)
print(b.ndim)
print(c.ndim)
print(arr1.ndim)
print(c.shape)
print(c.ndim)

1
2
3
0
(1, 3, 3)
3


In [18]:
#reshape
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [19]:
#shape
print(newarr.shape)

(4, 3)


In [20]:

#arange(creates array with range of val)
arnge = np.arange(10,100,3)
print(arnge)

[10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]


In [21]:
#zero
zero = np.zeros((5,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [22]:
#one
one = np.ones((2,7))
print(one)

[[1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1.]]


In [26]:
#eye
identity = np.eye(3)
print(identity)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#linspace
linespace = np.linspace(5,8,10)
print(linespace)

[5.         5.33333333 5.66666667 6.         6.33333333 6.66666667
 7.         7.33333333 7.66666667 8.        ]


In [40]:
#random values(randint)
randomval = np.random.randint(0,6,5)
print(randomval)
#rand
randomval2 = np.random.rand(10) #chooses b/w 0-1
print(randomval2)
#for array
ranval = np.random.randint(5,100,(5,6))
print(ranval)
#choice
course = np.random.choice(["Java", "Python", "React"])
print(course)


[1 0 2 2 4]
[0.18996301 0.50981752 0.94915032 0.95825578 0.74105418 0.32450138
 0.40204844 0.15055955 0.10208393 0.29765951]
[[12 75 87 48 40  7]
 [97 59 69 88 38 32]
 [40 16 92 46  5 12]
 [68 26 36 59 59 69]
 [73 35 63 47 41 27]]
Python


In [45]:
#sum
arr1 = np.array([[2,3,4,5,6],[7,2,4,1,8]])
a = np.array([[1,5,6,7,2],[3,6,2,5,4]])
suum = np.sum(arr1)
print(suum)
#2 arrays sum
sum = arr1 + a
print(sum)
#for arr1 with axis 0
sum1 = np.sum(arr1, axis =0)
print(sum1)
#for arr1 with axis 1
sum2 = np.sum(arr1, axis =1)
print(sum2)

42
[[ 3  8 10 12  8]
 [10  8  6  6 12]]
[ 9  5  8  6 14]
[20 22]


In [46]:
#mean
a = np.array([[1,5,6,7,2],[3,6,2,5,4]])
mean1 = np.mean(a)
print(mean1)

4.1


In [47]:
#standard deviation
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(np.std(arr))

14.142135623730951


In [56]:
arr = np.array([10, 20, 30, 40,60, 50])
m = np.min(arr)
print(m)
n = np.max(arr)
print(n)
o = np.argmin(arr)
print(o)
k =np.argmax(arr)
print(k)
#sort
b = np.sort(arr)
print(b)

10
60
0
4
[10 20 30 40 50 60]


In [61]:
#transpose
import numpy as np

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.transpose(arr))
print(arr.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [62]:
#dot
a = np.array([[1, 2],
              [3, 4]])

b = np.array([[5, 6],
              [7, 8]])

print(np.dot(a, b))

[[19 22]
 [43 50]]
